<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>FlatFile.Core.Attributes</RootNamespace>
    <AssemblyName>FlatFile.Core.Attributes</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../FlatFile.Core.Attributes/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FlatFile.Core.Modern/FlatFile.Core.Modern.csproj" />
  </ItemGroup>
</Project>
