<Project>
  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').Contains('.Modern'))">
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>forcewake</Authors>
    <Company>Pavel Nasovich</Company>
    <Description>FlatFile library for high-performance fixed-length and delimited file processing.</Description>
    <PackageProjectUrl>https://github.com/forcewake/FlatFile</PackageProjectUrl>
    <RepositoryUrl>https://github.com/forcewake/FlatFile</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').Contains('.Modern'))">
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>
</Project>
